services:
  - type: web
    name: flask-backend
    region: frankfurt
    plan: free
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: FRONTEND_URL
        value: https://superintegration.onrender.com
      - key: STRIPE_SECRET_KEY
        sync: false  # set in the Render dashboard

  - type: web
    name: react-frontend
    region: frankfurt
    plan: free
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://flask-backend.onrender.com  # update once backend service is created
